### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by augnustin** [marcan/letsencrypt-external#1]
I did: `sudo python /opt/letsencrypt-external/setup.py install` and got:

```
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-q3FuUR/mock-2.0.0/pbr-1.9.1-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-q3FuUR/mock-2.0.0/pbr-1.9.1-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/tmp/easy_install-q3FuUR/mock-2.0.0/pbr-1.9.1-py2.7.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1271, in evaluate_marker
    return cls.interpret(parser.expr(text).totuple(1)[1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1306, in interpret
    return op(nodelist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1223, in atom
    return cls.interpret(nodelist[2])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1306, in interpret
    return op(nodelist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1241, in comparison
    raise SyntaxError(repr(cop)+" operator not allowed in environment markers")
SyntaxError: '<' operator not allowed in environment markers
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-q3FuUR/mock-2.0.0/setup.cfg: SyntaxError: '<' operator not allowed in environment markers
```

Using:

```
sudo python --version
Python 2.7.6
```

Thanks for the help

**Comment by augnustin** [comment]
Fixed it through:

http://askubuntu.com/questions/683601/how-to-upgrade-python-setuptools-12-2-on-ubuntu-15-04

I was using `setup-tools version 3.3` ...

**Comment by jcoffland** [comment]
I also had to manually upgrade some packages:

```
pip install -U pbr
pip install -U mock
```
